'use client';

import { useState } from 'react';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { useLanguage } from '@/contexts/LanguageContext';
import { calculateReadingTime } from '@/lib/i18n/formatters';
import { Clock, Languages } from 'lucide-react';
import ReactMarkdown from 'react-markdown';

interface SummaryTabProps {
  summaryEn?: string | null;
  summarySw?: string | null;
  confidence?: number;
}

export function SummaryTab({ summaryEn, summarySw, confidence }: SummaryTabProps) {
  const { t, language } = useLanguage();
  const [selectedLang, setSelectedLang] = useState<'en' | 'sw'>(language);

  // Determine which summary to show
  const currentSummary = selectedLang === 'en' ? summaryEn : summarySw;
  const hasEnglish = !!summaryEn;
  const hasSwahili = !!summarySw;
  const hasAnySummary = hasEnglish || hasSwahili;

  // Fallback to available language if selected one doesn't exist
  const effectiveSummary = currentSummary || summaryEn || summarySw;
  const readingTime = effectiveSummary ? calculateReadingTime(effectiveSummary) : 0;

  if (!hasAnySummary) {
    return (
      <div className="py-12 text-center">
        <p className="text-muted-foreground">
          {language === 'en'
            ? 'No summary available for this document yet.'
            : 'Hakuna muhtasari unapatikana kwa hati hii bado.'}
        </p>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      {/* Header with metadata */}
      <div className="flex flex-wrap items-center justify-between gap-4 border-b pb-4">
        <div className="flex flex-wrap items-center gap-3">
          <h2 className="text-xl font-semibold">{t('summary.title')}</h2>
          {readingTime > 0 && (
            <Badge variant="outline" className="gap-1">
              <Clock className="h-3 w-3" aria-hidden="true" />
              {readingTime} {t('summary.readingTime')}
            </Badge>
          )}
        </div>

        {/* Language Toggle (only show if both languages available) */}
        {hasEnglish && hasSwahili && (
          <div className="flex items-center gap-2">
            <Languages className="h-4 w-4 text-muted-foreground" aria-hidden="true" />
            <div className="flex gap-1">
              <Button
                variant={selectedLang === 'en' ? 'default' : 'outline'}
                size="sm"
                onClick={() => setSelectedLang('en')}
                aria-pressed={selectedLang === 'en'}
              >
                EN
              </Button>
              <Button
                variant={selectedLang === 'sw' ? 'default' : 'outline'}
                size="sm"
                onClick={() => setSelectedLang('sw')}
                aria-pressed={selectedLang === 'sw'}
              >
                SW
              </Button>
            </div>
          </div>
        )}
      </div>

      {/* Summary Content */}
      <div className="prose prose-slate dark:prose-invert max-w-none">
        <ReactMarkdown>
          {effectiveSummary || ''}
        </ReactMarkdown>
      </div>

      {/* Disclaimer */}
      <div className="rounded-md bg-muted/50 p-4 text-sm text-muted-foreground">
        <p>
          {language === 'en'
            ? 'This summary was generated by AI and should be used as a guide. Please review the full document for complete details.'
            : 'Muhtasari huu ulizalishwa na AI na unapaswa kutumika kama mwongozo. Tafadhali kagua hati kamili kwa maelezo kamili.'}
        </p>
      </div>
    </div>
  );
}
